### ISSUE TITLE
Feature: Names to the Tracks

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-API#12]
Now we have authentication and we can track users we should put faces to the tracks added to the playlist.

This means the redis queue needs to store user IDs and will result in a change in what gets stored in the queue. Currently the Redis just stores a list of Spotify URIs. I suggest changing this to be a json object:

``` 
[
  '{"uri": "spotify:track:12345", "user": "abcsefg"}',
  '{"uri": "spotify:track:78910", "user": "hijklmn"}'
]
```

This would allow the `/player/queue` to return the user along with the track object:

```
track: { ... },
user: {
  name: 'User Name'
}
```

This would also need to apply to the `fm:player:current` redis key and thus allow the `/player/current` resource to render user data also.

This shouldn't effect most events such as `play`, `end`, `top` etc as we still only care about the track uri.

**Comment by jamesjwarren** [comment]
Sounds reasonable :+1:

**Comment by radeklos** [comment]
I've closed this issue because PR has been already merge in 2 weeks ago.
