### ISSUE TITLE
Return updated objects for PUT, POST, DELETE etc...

### ISSUE THREAD

**Issue by bcmrbvm** [thisissoon/FM-API#24]
When sending a `POST` request to `player/mute` for example the api returns `{"message": "200 OK"}`. It would be more useful for the FE if the API returned the updated object e.g. `{ mute: true }`. This is because angular's rest library updates the mute resource object with object returned from the response.

This also applies to all other end points.

**Comment by krak3n** [comment]
![](http://www.wildfactor.net/wp-content/uploads/2012/10/approved1.jpg)

**Comment by radeklos** [comment]
PR: https://github.com/thisissoon/FM-API/pull/29
