### ISSUE TITLE
Queue Total Tracks / Play Time etc

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-API#25]
We could provide some Queue stats to the FE to show in the player queue page.

Example Stats:

* Total Tracks in Queue (Technically the pagination `Pagination-Count` header)
* Total Play Time of the Queue (in ms)
* Most Active User in the Queue
* Popular Genre 

This data could also be returned in `POST` requests to the queue.

### Headers

We could use HTTP Headers since this would be data about the queue response data, something like:

`Queue-Total: 20`
`Queue-Play-Time: 5000`
`Queue-Active-User: 5db00514-2628-4017-99c1-01ffc601e696`

### Part of `/player/queue` Response

We could augment the API response for `/player/queue` to the meta data:

``` json
{
    "total": 20,
    "play_time": 5000,
    "active_user": " 5db00514-2628-4017-99c1-01ffc601e696",
    ...
    "tracks": [
        ...
    ]
}
```

### New Endpoint `/player/queue/meta` (or similar)

We could have an endpoint specific for return this data the FE could call when the queue changes on an event, so for example on:

* Queue Add
* Play Skip

``` json
{
    "total": 20,
    "play_time": 5000,
    "active_user": " 5db00514-2628-4017-99c1-01ffc601e696",
    ...
}
```

**Comment by krak3n** [comment]
Thoughts / Opinions on this one @peeklondon / @eopa / @jamesjwarren / @radeklos

**Comment by eopa** [comment]
I like the idea of returning just the raw data in the end points without the meta but if are going to go down the road of displaying meta data anyway we may as well return it all in `player/queue`

**Comment by peeklondon** [comment]
I prefer the specific endpoint called on change events I think - like the idea of a stats that can impact the interface (like most active) - also gives us the option to break the stats out eventually i.e. stats.thisissoon.fm

:)

**Comment by jamesjwarren** [comment]
I like the idea of these stats, sound cool. The separate endpoint sounds like a good idea as atm when a track is added we don't call the `play/queue` endpoint, so could be more flexible this way.

**Comment by krak3n** [comment]
We could do a mixture. The Queue endpoint would return the stats when the player FE initially loads and on the change events the FE calls the specific endpoint for the updated stats.

**Comment by radeklos** [comment]
https://github.com/thisissoon/FM-API/pull/34
