### ISSUE TITLE
Remove Track Endpoint

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-API#35]
A new endpoint so a user can remove their own tracks from the playlist. This means users can remove tracks they have added accidentally to the queue.

**Comment by bcmrbvm** [comment]
@krak3n the FE as well probably needs to implement a confirmation dialog when adding tracks

**Comment by krak3n** [comment]
@bcmrbvm could add more friction to the adding of tracks, also if we add an entire album the user might also want to remove one or 2 tracks from that.

Thought it might be handy if you change your mind too.

**Comment by bcmrbvm** [comment]
@krak3n We could have both, but i'll ask fred and ryan to give their opinion

**Comment by radeklos** [comment]
PR: https://github.com/thisissoon/FM-API/pull/38

**Comment by krak3n** [comment]
:boom:
