### ISSUE TITLE
User Stats

### ISSUE THREAD

**Issue by jamesjwarren** [thisissoon/FM-API#43]
Stats for a specific user:
- most played genres
- most played artist
- most played track
- total play time
- total plays

**Comment by jamesjwarren** [comment]
Feeling adventurous, going to have a look into this.
@krak3n / @radeklos what do you think about this being located at something like `/player/stats/user/:id`? Although atm I don't think we expose a list of users in the API which may be needed in order to navigate to such a route from the FE...

**Comment by krak3n** [comment]
@jamesjwarren Since these are use related rather than player related I think the resource should be `/user/:id/stats`

More RESTy :smile: 

Poke me or @radeklos if you need any help with the codebase.

**Comment by radeklos** [comment]
@jamesjwarren the stats are located at `/player/stats/`and it's not really relative to users but mostly to overall play history. But it would nice to have stats for every user separately as well.
