### ISSUE TITLE
user/:id/stats endpoint returns 500 error

### ISSUE THREAD

**Issue by edwardoparearyee** [thisissoon/FM-API#67]
On live this end point doesn't appear to work correctly, works locally though.

**Comment by krak3n** [comment]
Will check it out

**Comment by jamesjwarren** [comment]
Doesn't look like the trailing slash fix #58 is working on live, `https://api.thisissoon.fm/users/785bc064-0e08-4ea3-98d5-446e497bd213/stats` still redirects to `https://api.thisissoon.fm/users/785bc064-0e08-4ea3-98d5-446e497bd213/stats/`

**Comment by krak3n** [comment]
Yup it's a trailing slash issue

**Comment by krak3n** [comment]
I think the codes cool it's just the container has failed to update.

Redeploying...

**Comment by krak3n** [comment]
All sorted.
