### ISSUE TITLE
/current endpoint Access-Control-Expose-Headers should include "Paused" value

### ISSUE THREAD

**Issue by edwardoparearyee** [thisissoon/FM-API#76]
I'm unable to read the `Paused` value on the FE, I can see it in the response but the browser won't allow me access to it and I think it's because of this.

**Comment by edwardoparearyee** [comment]
This means that if the current track is paused when a user opens soon fm on their browser the FE will think the track is playing when it's paused.

**Comment by krak3n** [comment]
Yup, makes sense, will take a look when I can.

**Comment by jamesjwarren** [comment]
I think this is a duplicate of https://github.com/thisissoon/FM-API/issues/74

**Comment by edwardoparearyee** [comment]
sorry my bad, will close
