### ISSUE TITLE
Feature: Track Progress Bar

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-API#8]
Update the `/player/current` resource to return a percentage of track completion. A Redis key (`fm:player:progress`) will hold the current tracks elapsed time in seconds. We will know the tracks duration from our own API so should be able to provide a percentage figure.

Also consider a `/player/progress` resource.

See Also: thisissoon/FM-Frontend#84

**Comment by krak3n** [comment]
Player implementation here: thisissoon/FM-SoundWave#4

**Comment by radeklos** [comment]
@krak3n Do you want to hit the `/player/current` every second? I would rather moved this to FM-socket.

**Comment by krak3n** [comment]
@radeklos I don't expect the FE client to hit this every second. This will be used as a starter point for the FE to place an element on a progress bar at the right percentage and for the FE to tick itself from there.

There shouldn't be any socket events needed or for the FE to poll a resource every second.

**Comment by radeklos** [comment]
PR: https://github.com/thisissoon/FM-API/pull/28
